### ISSUE TITLE
Traveller class

### ISSUE THREAD

**Issue by slithy** [slithy/bbw-traveller#13]
For crew members and important passengers (PC and NPC)

You don't need a full implementation of all the rules for Travellers, but a few basic things would be useful:

* Name
* UPP
* For crew: Crew position and salary, shareholding of the starship, list of skills (at least the ones relevant to Starship operations (pilot, engineering, astrogation, steward, broker, streetwise, ...), with the skill level for each)
* For passengers: Type of passage (High, Middle, Basic, Low) → determines how much they should pay for each Jump

Crew and passengers can be maintained as lists in the starship. For unimportant NPC passengers, have a quick way to bulk add/remove them, like "add_passengers middle=1 basic=5 low=6" and "remove_passengers" when you get to a destination.

**Comment by cattabiani** [comment]
I did not want to add all this information for the passengers. atm I have just a "tank" of passengers. For example, 20 seats that can be filled with crew or passengers. I thought that a "high passenger" can be represented as 2 middle passengers. If you want I can add the same system for cargo e give them a value (as items). That should work out of the box

**Comment by cattabiani** [comment]
I am losing track of what is really open and what is already implemented in starship2. I will close all the issues that are already solved in using that branch as the "de facto" main
