### ISSUE TITLE
World Class

### ISSUE THREAD

**Issue by slithy** [slithy/bbw-traveller#14]
It would be useful to have a class for info about the current world.

The basic info is the Universal World Profile (UWP), which is like the UPP for Travellers. The basic UWP is defined here: https://wiki.travellerrpg.com/Universal_World_Profile

Heya, for example is **Spinward Marches/Regina 0802 B687754-5 I Ri Ag Ga Lt G** (see Library data).

* B = class B starport. This determines berthing costs and what kind of fuel is available
* 6 = world diameter. Multiply by 1600 to get diameter in Km. Minimum jump distance is (diameter in Km)*100. Transit time in seconds from the world to/from jump distance = 2 * sqrt(jump distance/ship's M-drive rating)
* 8 = atmosphere type
* 7 = hydrography, multiply by 10 to get approximate surface water coverage. Determines if you can scoop water for fuel. Except in the cases of corrosive or exotic atmospheres, where the surface liquid is not water, maybe it's ammonia or something.
* 7 = population, in powers of 10
* 5 = government type
* 4 = law level
* last number (-5) is tech level
* I = Imperial world
* Ri Ag Ga Lt = trade codes (Rich, Agricultural, Garden world, Low technology). Determines what trade goods are available.
* G = gas giant

If you really want to go over-the-top with this, Traveller Map has an API https://travellermap.com/doc/api, but I think we don't need to go that far just yet ...!

**Comment by cattabiani** [comment]
I am losing track of what is really open and what is already implemented in starship2. I will close all the issues that are already solved in using that branch as the "de facto" main
