### ISSUE TITLE
add galaxy

### ISSUE THREAD

**Issue by cattabiani** [slithy/bbw-traveller#19]
Trading and jumping requires knowledge of the planet and their distances. I this we should add:
- a planet object
- a library of distances
- the galaxy object

**Comment by slithy** [comment]
TravellerMap has all the world data you need, including UWP and Trade Codes. You can download the data and there is even an API. See documentation here: https://travellermap.com/doc/secondsurvey and here: https://travellermap.com/doc/api

"galaxy" is a bit ambitious. Try zooming out of TravellerMap and you will see how tiny Charted Space is compared to the galaxy.

The API allows you to do things like list all worlds within Jump distance of your starship: https://travellermap.com/doc/api#jump-worlds-return-a-list-of-worlds-within-n-parsecs. So in principle you don't need to implement this yourself.

Unlike the Traveller Wiki, TravellerMap allows you to select the correct data for different time periods. Pass the parameter "milieu=M1105" to get the data for the time period we are playing in (actually I think this is the default).

The API also allows you to generate graphical maps around your current location.

**Comment by cattabiani** [comment]
- the scraping requires a totally new part of bbw. It will not be ready for wed.
- we still need the ability to create new worlds (in case you want to add secret worlds out there)
- I need an object for a collection of planets (and maybe distances). Galaxy to me sounds like a good name to me. Even if only a small part of the galaxy is colonized this does not stop you from creating worlds (anywhere you want) and they should go in this object. 3rd imperium or map sound even worse. I am very happy to receive suggestions on this

I think a bbwobject for planets and galaxy (names can change if you have better suggestions) is still needed. We can connect it after to a scraper to automatically create worlds that exist. Given how often we fly I do not think it is so important

**Comment by cattabiani** [comment]
... maybe `charted space`?

**Comment by slithy** [comment]
I would use `World` rather than planet, as in the book the stats are called the UWP (Universal World Profile).

Worlds are collected into subsectors and sectors (1 sector = 4x4 grid of subsectors. e.g. Regina is a subsector, Spinward Marches is a sector). Maybe you don't care about representing that.

Charted Space is all worlds which have been surveyed, so that's a good name for the collection of all known worlds.

**Comment by cattabiani** [comment]
I was using planet because here it is written that they are interchangeable:
https://wiki.travellerrpg.com/Planet

anyway, np, as you prefer. Atm I do not need sectors and subsectors. I have an idea to compute distances from the hex location. 

Ok, for charted space

**Comment by cattabiani** [comment]
I am losing track of what is really open and what is already implemented in starship2. I will close all the issues that are already solved in using that branch as the "de facto" main
