### ISSUE TITLE
`print_long_message` problems

### ISSUE THREAD

**Issue by cattabiani** [slithy/bbw-traveller#2]
IMHO there are 2 problem with this function:

- if there are no `\n` the message is not really split and it can fail to send
- even if there are, the sending becomes very slow since it splits every new line

the first one is probably not a real problem but the second one can be annoying.

**Comment by slithy** [comment]
An alternative would be to find the last `\n` before the 2000 char limit and split the text in two there. Send everything in the first part. Apply the same algorithm to the second part.

**Comment by cattabiani** [comment]
I have already a branch ready
