### ISSUE TITLE
Calendar class

### ISSUE THREAD

**Issue by slithy** [slithy/bbw-traveller#4]
Another important class to create is the Calendar.

Dates are recorded as Year and Day of Year. There are 364 days in a year (52 weeks, or 13 4-week "months" which is the basic unit of time for many financial transactions, like mortgage payments and salaries).

The calendar should be saved/loaded to the JSON file along with the Starship. There should be methods to set the date, display the date and advance the date by a specified number of days (default: 1). Days of the week are called Oneday, Twoday, etc.

If incrementing the date passes a 4-week boundary, it should return a bool to indicate this. The command can display a message to indicate that payments are due.

**Comment by cattabiani** [comment]
what is the current year? So I have a vague idea of the order of magnitude of the numbers I am working with

**Comment by slithy** [comment]
Simple answer: the current year is 1105 of the Third Imperium.

Detailed answer: see **Dating Systems** in Library Data.

Note that years have 365 days, which is equal to 52 weeks of 7 days plus one holiday day.

The first day of the year (001) doesn't form part of any week and is simply called "Holiday".

The days of each week are named based upon their ordinal position in the week: Wonday or 1day, Tuday or 2day, Thirday or 3day, Forday or 4day, Fiday or 5day, Sixday or 6day, Senday or 7day.

So in every year, day 002 is always 1day, day 365 is always 7day and so on.

To calculate payment dates for mortgage, salaries, etc. just skip over Holiday and make the payment date every 4th Senday.

**Comment by cattabiani** [comment]
I am losing track of what is really open and what is already implemented in starship2. I will close all the issues that are already solved in using that branch as the "de facto" main
