### ISSUE TITLE
inventory

### ISSUE THREAD

**Issue by cattabiani** [slithy/bbw-traveller#7]
To be added

**Comment by slithy** [comment]
The important inventory is contents of the Starship cargo bay. Optionally you could also have the contents of the Ship's Locker but this is less important. IMO adding inventory for Travellers is too much. Personal inventory will change for each planet's situation, just writing it down on paper is easier.

**Cargo Bay**

Cargo bay items can include:

* Vehicles like the Air/Raft and G/Carrier (variable tons)
* Mail cannisters (5 tons each)
* Freight (each cargo lot can be 1Dx10 tons, 1Dx5 tons, 1D tons for major/minor/incidental cargo lots. You have to take the entire lot ot none at all.)
* Speculative cargos

Mail and freight are simple: you deliver them and get paid (Cr. 25000 per mail cannister, Cr. 1000/ton of freight). If freight delivery is late, there is a penalty of 1D+4 x10%.

Speculative cargo needs a few more details: The type of cargo (Electronics, Pharmaceuticals, Live Animals, Illegal Weapons, ...), the number of tons, the tech level of the world where you bought it, the price you paid. When you sell it you will be offered a sale price which will be different (hopefully more) than the purchase price.

**Ship's Locker**

Contains vacc suits, weapons, scientific equipment etc. which is needed for adventuring on-planet but which individuals don't lug around with them every time you visit a starport. When you visit a planet you should choose which equipment you need for that planet. People can just note on paper what items they have for any given expedition and keep the ship's locker as a master list of what is available.

Personal items like weapnos and armour could also be stored in the ship's locker and taken out when needed, so you might want to note who each item belongs to.

**Comment by cattabiani** [comment]
yes, inventory was a general term for container.I have a solution that works for all the problems

**Comment by cattabiani** [comment]
I am losing track of what is really open and what is already implemented in starship2. I will close all the issues that are already solved in using that branch as the "de facto" main
