### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by cattabiani** [slithy/bbw-traveller#8]

**Comment by slithy** [comment]
I would implement ship's funds but let each person keep track of their personal cash.

* How many credits are in the ship's operations fund
* You can also have a second fund for maintenance. Every 4 weeks transfer money from ship's funds to maintenance fund for the annual maintenance overhaul
* Buying and selling cargo subtracts and adds to operations fund
* Taking on passengers adds funds
* Operating costs are deducted for berthing costs in a starport, refuelling (unless at a gas giant), etc.
* Regular operations and life support costs can be deducted as time passes (needs the calendar to be implemented)
* Every 4 weeks: mortgage payment and crew salaries

**Comment by cattabiani** [comment]
additional features:
- running ledger

When we do a jump we get the money on loading or unloading? At the beginning or at the end of a flight? (may we not have an hybrid system?)

**Comment by slithy** [comment]
Passengers pay in advance. Mail is paid in advance. Freight cargo is paid on delivery. Speculative cargo is paid when you sell it.

**Comment by cattabiani** [comment]
I knew it was hybrid... Uff

**Comment by cattabiani** [comment]
I am losing track of what is really open and what is already implemented in starship2. I will close all the issues that are already solved in using that branch as the "de facto" main
